sudo: required
services: 
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .


script: 
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  name: "docker-react"
  env: " DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-452027285533"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  